cat("\014")
item_code=c(1001,1002,1003,1004,1005)
item_cat=c("Electronics","Desktop Supplies","Office Supplies","USB","CD Drive")
item_price=c(700,300,3500,400,800)
item_Df<-data.frame(item_code,item_cat,item_price)
cat("\nDisplay Items data table\n\n")
print(item_Df)
Items_Subset_1<-subset.data.frame(item_Df,subset=item_price>=350)
cat("\n\n(a).Display subset of items data table where item_price>=350\n\n")
print(Items_Subset_1)
Items_Subset_2<-subset.data.frame(item_Df,subset=(item_cat=="Office Supplies")|(item_cat=="Desktop Supplies\n\n"))
cat("\n\n(b).Display subset of items data table where the category is either Office Supplies or Desktop Suplies\n\n")
print(Items_Subset_2)
Items_Subset_3<-subset.data.frame(item_Df,subset=(item_price>=300)&(item_price<=700))
cat("\n\n(d).Display subset of items data table where the itemprice between 300 and 700\n\n")
print(Items_Subset_3)
total_price<-sum(item_Df$item_price)
cat("\n\n(d).Display Total of items price column fro items data table\n\n")
cat("Total Price:",total_price)
item_code=c(1001,1002,1003,1008,1009)
item_QtyOnHand=c(100,230,140,90,45)
item_ReoederLv1=c(1,3,1,2,3)
cat("\n\n (e).New data table items Details\n\n")
itemDetails<-data.frame(item_code,item_QtyOnHand,item_ReoederLv1)
print(itemDetails)
Merged_ItemsDetail<-merge.data.frame(item_Df,itemDetails,by="item_code")
cat("\n\n(f).Display Merged Data Tables\n\n")
print(Merged_ItemsDetail)
